version: '3.3'
services:

  postgres:
    image: postgres:12
    ports:
      - '5555:5432'
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASS}
    networks:
      - awesome

  pgadmin:
    image: dpage/pgadmin4:6.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '5656:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - awesome

  salerno-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT}:3000"
    restart: always
    depends_on:
      - postgres
    networks:
      - awesome
    env_file:
      - ../.env

volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge
